[project]
name = "my_project"
description = "A T data analysis project"

[dependencies]
# T packages this project depends on
# Format: package = { git = "repository-url", tag = "version" }
# Example:
hello_t = { git = "https://github.com/b-rodrigues/hello_t", tag = "v0.0.3" }

[t]
# Minimum T language version required
min_version = "0.5.0"
